### PR TITLE
Update ghcide dependency for various plugins

### PR DESCRIPTION
**Pull request by hololeap**
`hls-class-plugin-1.0.1.1` imports `Development.IDE.GHC.Compat.Util`, which doesn't exist until `ghcide-1.5.0`

```
Building library for hls-class-plugin-1.0.1.1..
[1 of 1] Compiling Ide.Plugin.Class ( src/Ide/Plugin/Class.hs, dist/build/Ide/Plugin/Class.o, dist/build/Ide/Plugin/Class.dyn_o )

src/Ide/Plugin/Class.hs:27:1: error:
    Could not find module ‘Development.IDE.GHC.Compat.Util’
    Perhaps you meant
      Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
      Development.IDE.GHC.Util (from ghcide-1.4.2.2)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
27 | import           Development.IDE.GHC.Compat.Util
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2368"></a>

### CODE REVIEW

**Review by jneira — APPROVED** [review]
Good catch, thanks for the pr fixing it
Out of curiosity, are you installing hls from hackage for any specific reason?

**Comment by jneira** [comment]
A hackage revision will be needed to fix the uploaded package

**Comment by hololeap** [comment]
I'm packaging for Gentoo which tends to catch all sorts of unnoticed bugs. It pulls packages from hackage and uses cabal v1 under the hood to compile.

**Review by jneira — APPROVED** [review]
many many thanks for fixing bounds, we are not checking backwards compat in our hackage workflow, will do revisions asap

**Comment by jneira** [comment]
is it still a wip? maybe it needs update more plugins?

**Comment by hololeap** [comment]
@jneira Still a WIP until I confirm they build with `ghcide-1.5.0`. Would it be better if this was one large commit instead of a bunch of small ones?

**Comment by jneira** [comment]
ok, that way is fine to me, we usually do squash+merge to master

**Comment by hololeap** [comment]
All these build with `ghcide-1.5.0`. I just wanted to double check:)

**Comment by hololeap** [comment]
Just FYI, I didn't get a chance to check `hls-fourmolu-plugin` with `ghcide-1.4.2.2`, but it builds fine with `ghcide-1.5.0`

**Comment by jneira** [comment]
Needed revisons (`ghcide ^>=1.5.0`), last version of:

* [ ] hls-test-utils
* [ ] hls-class-plugin
* [ ] hls-fourmolu-plugin
* [ ] hls-hlint-plugin
* [ ] hls-ormolu-plugin
* [ ] hls-retrie-plugin
* [ ] hls-splice-plugin
* [ ] hls-stylish-haskell-plugin
* [ ] hls-tactics-plugin

**Comment by jneira** [comment]
@hololeap all plugins revised!
