### ISSUE TITLE
Failed build with ghc 8.8.2

### ISSUE THREAD

**Issue by robrix** [haskell/haskell-language-server#994]
Building with ghc 8.8.2 fails with a couple of errors related to out of scope data constructors, presumably changed in the latest compiler:

```
src/Development/IDE/GHC/CPP.hs:143:22: error:
    Not in scope: data constructor ‘LlvmVersion’
    |
143 |                Just (LlvmVersion n) -> [ "-D__GLASGOW_HASKELL_LLVM__=" ++ format (n,0) ]
    |                      ^^^^^^^^^^^

src/Development/IDE/GHC/CPP.hs:144:22: error:
    Not in scope: data constructor ‘LlvmVersionOld’
    |
144 |                Just (LlvmVersionOld m n) -> [ "-D__GLASGOW_HASKELL_LLVM__=" ++ format (m,n) ]
    |                      ^^^^^^^^^^^^^^
```

On 703bb82a1d3b690c7ef2b8cb7d28c0ac5171dd0c, `HEAD` at time of writing.
