### ISSUE TITLE
hls-splice-plugin: can't compile with GHC 9.2.2

### ISSUE THREAD

**Issue by maerten** [haskell/haskell-language-server#2796]
### Your environment

Which OS do you use:
MacOS

Which LSP client (editor/plugin) do you use:
Directly starting haskell-language-server from terminal while trying to install it properly.

Describe your project (alternative: link to the project):
haskell project using QuasiQuotes language extension

### Steps to reproduce
Try compiling hls after enabling the hls-splice-plugin in stack-9.2.yaml 

### Expected behaviour
Not entirely expected, but desired behavior is that it just compiles without issue :) 

### Actual behaviour
Compilation error related to Language.Haskell.GHC.ExactPrint

### Include debug information
```
hls-splice-plugin                 > [2 of 2] Compiling Ide.Plugin.Splice
hls-splice-plugin                 >
hls-splice-plugin                 > /private/var/folders/0c/zmpjp7l568xcvnt49pkkn5p00000gn/T/stack-c77dc10926bf43ba/hls-splice-plugin-1.0.1.0/src/Ide/Plugin/Splice.hs:55:51: error:
hls-splice-plugin                 >     Module
hls-splice-plugin                 >     ‘Language.Haskell.GHC.ExactPrint’
hls-splice-plugin                 >     does not export
hls-splice-plugin                 >     ‘setPrecedingLines’
hls-splice-plugin                 >    |
hls-splice-plugin                 > 55 | import           Language.Haskell.GHC.ExactPrint (setPrecedingLines,
hls-splice-plugin                 >    |                                                   ^^^^^^^^^^^^^^^^^
```

The README at https://github.com/alanz/ghc-exactprint shows there is a new (and perhaps backwards incompatible) version for GHC 9.2

**Comment by maerten** [comment]
Yep, 9.2.2 does compile, but the splice plugin seems to be disabled by default (in stack-9.2.yaml).   what if you enable the splice plugin before compiling hls? Does that compile for you too?

**Comment by drsooch** [comment]
Ah yes, apologies. It's disabled in cabal-ghc92.project file.

**Comment by drsooch** [comment]
There is a meta-issue for 9.2.* support here: #2179 

hls-splice-plugin was noted as working in 9.2.1, which is no longer true.

**Comment by michaelpj** [comment]
Old, and the configs have changed a lot since then.
