### ISSUE TITLE
Build with GHC 9.10.3-rc1 fails

### ISSUE THREAD

**Issue by andreasabel** [haskell/haskell-language-server#4678]
I am trying to follow `ghcup`s helpful hint 3 on how to get HLS for GHC 9.10.3 (RC1: GHC 9.10.2.20250725).
```
[ Warn  ] GHC-9.10.2.20250725 appears to have no corresponding HLS-2.11.0.0 binary.
[ ...   ] Haskell IDE support may not work.
[ ...   ] You can try to either: 
[ ...   ]   1. Install a different HLS version (e.g. downgrade for older GHCs)
[ ...   ]   2. Install and set one of the following GHCs: [9.12.2, 9.10.2, 9.8.4, 9.6.7, 9.4.8]
[ ...   ]   3. Let GHCup compile HLS for you, e.g. run: ghcup compile hls -g 2.11.0.0 --ghc 9.10.2.20250725 --cabal-update
```
`ghcup compile hls -g 2.11.0.0 --ghc 9.10.2.20250725 --cabal-update` fails, and from the `cabal.log` I can see the reason:
```
[3 of 8] Compiling Ide.Plugin.SemanticTokens.SemanticConfig ( ... )
plugins/hls-semantic-tokens-plugin/src/Ide/Plugin/SemanticTokens/SemanticConfig.hs:19:51: error: [GHC-51433]
    In the import of ‘Ide.Plugin.Properties’:
      a data type called ‘PropertyKey’ is exported,
      but its subordinate item ‘PropertyKey’
      is not in the type namespace.
   |
19 |                                                   PropertyKey (type PropertyKey),
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

plugins/hls-semantic-tokens-plugin/src/Ide/Plugin/SemanticTokens/SemanticConfig.hs:20:51: error: [GHC-51433]
    In the import of ‘Ide.Plugin.Properties’:
      a data type called ‘PropertyType’ is exported,
      but its subordinate item ‘TEnum’ is not in the type namespace.
   |
20 |                                                   PropertyType (type TEnum),
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
```
I tried the same command with GHC 9.10.2 and that succeeded: `ghcup compile hls -g 2.11.0.0 --ghc 9.10.2`.

**Comment by andreasabel** [comment]
Some context:
https://github.com/haskell/haskell-language-server/blob/b8c9b8466afe5521ce5ae3b2c7195cafe8dda371/plugins/hls-semantic-tokens-plugin/src/Ide/Plugin/SemanticTokens/SemanticConfig.hs#L17-L20
https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/explicit_namespaces.html#extension-ExplicitNamespaces

I can reproduce this on `master` with GHC-9.10.3-rc1, while GHC-9.10.2 compiles everything fine.
So I suppose this is a regression in GHC-9.10.3.

Upstream issue: https://gitlab.haskell.org/ghc/ghc/-/issues/26250

**Comment by andreasabel** [comment]
Ok, this is not a regression in GHC, but a bugfix, so HLS is wrong here:
- https://gitlab.haskell.org/ghc/ghc/-/issues/22581

**Comment by andreasabel** [comment]
Using PR #4679 I managed to build HLS and linking to it from `~/.ghcup/bin` I now have HLS for GHC 9.10.3-rc1 working. 🚀
