### ISSUE TITLE
hls-hlint-plugin-1.1.2.0 fails to build with ghc-9.2?

### ISSUE THREAD

**Issue by juhp** [haskell/haskell-language-server#3522]
### Your environment

Which OS do you use?  Fedora
Which version of GHC do you use and how did you install it? Fedora ghc-9.2.6
Which version of HLS do you use and how did you install it? 1.9.1.0

### Steps to reproduce
https://download.copr.fedorainfracloud.org/results/petersen/haskell-language-server/fedora-rawhide-x86_64/05634908-haskell-language-server/builder-live.log.gz

### Expected behaviour
hls-hlint-plugin to build

### Actual behaviour
Fails to build (with hlint-3.4.1)
```
Building library for hls-hlint-plugin-1.1.2.0..
[1 of 1] Compiling Ide.Plugin.Hlint ( src/Ide/Plugin/Hlint.hs, dist/build/Ide/Plugin/Hlint.o, dist/build/Ide/Plugin/Hlint.dyn_o )

src/Ide/Plugin/Hlint.hs:237:42: error:
    * Couldn't match expected type `SrcSpan'
                  with actual type `ghc-9.2.6:GHC.Types.SrcLoc.SrcSpan'
      NB: `SrcSpan'
            is defined in `GHC.Types.SrcLoc'
                in package `ghc-lib-parser-9.2.5.20221107'
          `ghc-9.2.6:GHC.Types.SrcLoc.SrcSpan'
            is defined in `GHC.Types.SrcLoc' in package `ghc-9.2.6'
    * In the second argument of `($)', namely `ideaSpan idea'
      In the `_range' field of a record
      In the expression:
        Diagnostic
          {_range = srcSpanToRange $ ideaSpan idea, _severity = Just DsInfo,
           _code = Just (InR $ T.pack $ codePre ++ ideaHint idea),
           _source = Just "hlint", _message = idea2Message idea,
           _relatedInformation = Nothing, _tags = Nothing}
    |
237 |             _range    = srcSpanToRange $ ideaSpan idea
    |                                          ^^^^^^^^^^^^^

src/Ide/Plugin/Hlint.hs:261:40: error:
    * Couldn't match expected type `SrcSpan'
                  with actual type `ghc-9.2.6:GHC.Types.SrcLoc.SrcSpan'
      NB: `SrcSpan'
            is defined in `GHC.Types.SrcLoc'
                in package `ghc-lib-parser-9.2.5.20221107'
          `ghc-9.2.6:GHC.Types.SrcLoc.SrcSpan'
            is defined in `GHC.Types.SrcLoc' in package `ghc-9.2.6'
    * In the first argument of `srcSpanToRange', namely `l'
      In the `_range' field of a record
      In the expression:
        Diagnostic
          {_range = srcSpanToRange l, _severity = Just DsInfo,
           _code = Just (InR "parser"), _source = Just "hlint",
           _message = T.unlines [T.pack msg, T.pack contents],
           _relatedInformation = Nothing, _tags = Nothing}
    |
261 |             _range    = srcSpanToRange l
    |                                        ^

src/Ide/Plugin/Hlint.hs:332:48: error:
    * Couldn't match type `Extension'
                     with `ghc-boot-th-9.2.6:GHC.LanguageExtensions.Type.Extension'
      Expected: [ghc-boot-th-9.2.6:GHC.LanguageExtensions.Type.Extension]
        Actual: [Extension]
      NB: `ghc-boot-th-9.2.6:GHC.LanguageExtensions.Type.Extension'
            is defined in `GHC.LanguageExtensions.Type'
                in package `ghc-boot-th-9.2.6'
          `Extension'
            is defined in `GHC.LanguageExtensions.Type'
                in package `ghc-lib-parser-9.2.5.20221107'
    * In the `enabledExtensions' field of a record
      In the second argument of `($)', namely
        `flags {enabledExtensions = hlintExts}'
      In a stmt of a 'do' block:
        return $ flags {enabledExtensions = hlintExts}
    |
332 |           return $ flags { enabledExtensions = hlintExts }
    |                                                ^^^^^^^^^

src/Ide/Plugin/Hlint.hs:349:12: error:
    * Couldn't match type `ghc-boot-th-9.2.6:GHC.LanguageExtensions.Type.Extension'
                     with `Extension'
      Expected: [Extension]
        Actual: [ghc-boot-th-9.2.6:GHC.LanguageExtensions.Type.Extension]
      NB: `Extension'
            is defined in `GHC.LanguageExtensions.Type'
                in package `ghc-lib-parser-9.2.5.20221107'
          `ghc-boot-th-9.2.6:GHC.LanguageExtensions.Type.Extension'
            is defined in `GHC.LanguageExtensions.Type'
                in package `ghc-boot-th-9.2.6'
    * In the first argument of `return', namely hscExts'
      In a stmt of a 'do' block: return hscExts'
      In the expression:
        do dflags <- getFlags
           let hscExts = EnumSet.toList (extensionFlags dflags)
           let hscExts' = mapMaybe (readExtension . show) hscExts
           return hscExts'
    |
349 |     return hscExts'
    |            ^^^^^^^^

src/Ide/Plugin/Hlint.hs:620:84: error:
    * Couldn't match type `ghc-9.2.6:GHC.Types.SrcLoc.SrcSpan'
                     with `SrcSpan'
      Expected: Idea -> SrcSpan
        Actual: Idea -> ghc-9.2.6:GHC.Types.SrcLoc.SrcSpan
      NB: `SrcSpan'
            is defined in `GHC.Types.SrcLoc'
                in package `ghc-lib-parser-9.2.5.20221107'
          `ghc-9.2.6:GHC.Types.SrcLoc.SrcSpan'
            is defined in `GHC.Types.SrcLoc' in package `ghc-9.2.6'
    * In the second argument of `(.)', namely `ideaSpan'
      In the second argument of `(.)', namely `toRealSrcSpan . ideaSpan'
      In the expression:
        (srcSpanStartLine &&& srcSpanStartCol) . toRealSrcSpan . ideaSpan
    |
620 |                 ideaPos = (srcSpanStartLine &&& srcSpanStartCol) . toRealSrcSpan . ideaSpan
    |                                                                                    ^^^^^^^^
Error: cabal: Failed to build hls-hlint-plugin-1.1.2.0 (which is required by
exe:haskell-language-server-wrapper from haskell-language-server-1.9.1.0 and
exe:haskell-language-server from haskell-language-server-1.9.1.0). See the
build log above for details.
```

**Comment by juhp** [comment]
Ah mpj pointed out https://github.com/haskell/haskell-language-server/blob/master/cabal.project#L65 to on matrix
