### ISSUE TITLE
Build with aeson >= 2.0

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2477]
* I am continuing @Anton-Latukha's work from #2473 in this branch https://github.com/jneira/haskell-language-server/tree/brittany-9.0.1
* As the new version of brittany needs aeson >= 2.0 we have to jump into that wagon (or patch brittany to support aeson <= 2.0 and ghc-9.0.1 at same time)

* So we have to go down the rabbit hole to get aeson-2 for ghc >= 9.01:
  * [x] https://github.com/ennocramer/floskell/issues/68
  * [x] https://github.com/haskell/lsp/issues/373
  * [ ] https://github.com/haskell/stylish-haskell/issues/387

* Upstream brittany deps which need support for ghc-9.0.1 (so needed to make available brittany+9.0.1 in hackage)
  * [ ] multistate: https://github.com/lspitzner/multistate/pull/8
  * [ ] data-tree-print: https://github.com/lspitzner/data-tree-print/pull/3
  * [ ] butcher: https://github.com/lspitzner/butcher/pull/8

* Needed to support aeson-2 for ghc < 9.0.1 (not mandatory)
  * [x] https://github.com/ndmitchell/hlint/issues/1328 
  * [ ] Brittany support for aeson-2.0 + ghc < 9.0.1

**Comment by jneira** [comment]
Of course floskell is [not buildable with aeson >= 2.0](https://github.com/jneira/haskell-language-server/runs/4503799254?check_suite_focus=true):

```
src/Floskell/ConfigFile.hs:93:26: error:
Error:     • Couldn't match type: HashMap.HashMap k0 JSON.Value
                     with: Data.Aeson.KeyMap.KeyMap JSON.Value
      Expected: JSON.Object
        Actual: HashMap.HashMap k0 JSON.Value
    • In the first argument of ‘JSON.Object’, namely
        ‘(HashMap.unionWith mergeJSON l r)’
      In the expression: JSON.Object (HashMap.unionWith mergeJSON l r)
      In an equation for ‘mergeJSON’:
          mergeJSON (JSON.Object l) (JSON.Object r)
            = JSON.Object (HashMap.unionWith mergeJSON l r)
   |
93 |             JSON.Object (HashMap.unionWith mergeJSON l r)
   |                          ^^^^^^^^^^^^^^^
```

**Comment by jneira** [comment]
> or patch brittany to support aeson <= 2.0 and ghc-9.0.1 at same time

given aeson >= 2.0 inlcudes an important security related patch i thik we should try to use it here

**Comment by jneira** [comment]
PR to add aeson >= 2.0 to floskell: https://github.com/ennocramer/floskell/pull/69

**Comment by jneira** [comment]
hls-plugin-api needs to be patched, several errors like:

```
src\Ide\Plugin\Properties.hs:240:25: error:
Error:     • Couldn't match expected type ‘A.Key’ with actual type ‘T.Text’
    • In the second argument of ‘(A..:)’, namely ‘keyName’
      In a stmt of a 'do' block: txt <- o A..: keyName
      In the expression:
        do txt <- o A..: keyName
           if txt `elem` enumValues then
               pure txt
           else
               fail
                 $ "invalid enum member: "
                     <> show txt <> ". Expected one of " <> show enumValues
    |
240 |           txt <- o A..: keyName

    | 
```

**Comment by jneira** [comment]
After checking master version of lsp packages works with hls, including the test suite, will release new versions

**Comment by michaelpj** [comment]
I suspect we can sort out `hls-plugin-api` in a way that works nicely both pre- and post-2.0

**Comment by jneira** [comment]
> I suspect we can sort out `hls-plugin-api` in a way that works nicely both pre- and post-2.0

@michaelpj 
https://github.com/haskell/aeson/issues/881#issuecomment-944920664 suggests create a `fromKey`/`toKey` and make it work with `Text` and `Aeson.Key` using CPP but i would love to do it without cpp conditions (like you did for lsp, using hte Aeson api differently)

**Comment by jneira** [comment]
stylish-haskell also would need support for aeson >= 2.0: https://github.com/haskell/stylish-haskell/issues/387

**Comment by jneira** [comment]
And packages (hls-plugin-api, ghcide,..) need to be adapted to the new lsp version, which supports in turn aeson-2.
As the aeson-2 thin is getting more complex, i would focus in lsp packages first, leveraging @michaelpj work here: https://github.com/michaelpj/haskell-language-server/tree/mpj/wip-hls-lsp-upgrade
I am continuing the work there in this one https://github.com/haskell/haskell-language-server/tree/hls-lsp-upgrade

**Comment by michaelpj** [comment]
> given aeson >= 2.0 inlcudes an important security related patch i think we should try to use it here

Just to reiterate on this, I'm fairly sure that the security issue is not relevant for HLS as it isn't parsing untrusted input.

**Comment by jneira** [comment]
I am gonna reopen to track the possible use of aeson 2 for ghc < 9.0.1 and brittany upstream deps needing support for ghc >= 9.0.1

**Comment by michaelpj** [comment]
> I am gonna reopen to track the possible use of aeson 2 for ghc < 9.0.1

Do we need to do this?

**Comment by jneira** [comment]
> > I am gonna reopen to track the possible use of aeson 2 for ghc < 9.0.1
> 
> Do we need to do this?

No strictly, but we can take ride of some pesky `fromString . unpack` which can be reaplaced with directs `Aeson.Key.fromText`.
And well we could use new aeson-2.x versions with possible new bug fixes or perf improvements for ghc < 9.0.1

**Comment by michaelpj** [comment]
IMO it's not worth spending lots of effort on. We can force it once we're only supporting GHC 9 :p

**Comment by jneira** [comment]
ok, i've moved the pending tasks to #297 and give up on get aeson-2.0 support for ghc < 9.0.1 so closing this
