### ISSUE TITLE
apply-refact 0.9.0.0 compatibility

### ISSUE THREAD

**Issue by maralorn** [haskell/haskell-language-server#1240]
At least one plugin, hls-hlint-plugin, does (as of hls 0.8.0) not compile with apply-refact 0.9.0.0. Until this is fixed the plugin should get an upper bound on apply-refact in the cabal file.

The build error is this:
```
Building library for hls-hlint-plugin-0.1.0.0..
[1 of 1] Compiling Ide.Plugin.Hlint ( src/Ide/Plugin/Hlint.hs, dist/build/Ide/Plugin/Hlint.o, dist/build/Ide/Plugin/Hlint.dyn_o )

src/Ide/Plugin/Hlint.hs:365:24: error:
    • Couldn't match expected type ‘IO String’
                  with actual type ‘[String] -> IO String’
    • Probable cause: ‘applyRefactorings’ is applied to too few arguments
      In the second argument of ‘(<$>)’, namely
        ‘applyRefactorings Nothing commands temp’
      In the first argument of ‘catches’, namely
        ‘(Right <$> applyRefactorings Nothing commands temp)’
      In a stmt of a 'do' block:
        (Right <$> applyRefactorings Nothing commands temp)
          `catches`
            [Handler $ \ e -> return (Left (show (e :: IOException))),
             Handler $ \ e -> return (Left (show (e :: ErrorCall)))]
    |
365 |             (Right <$> applyRefactorings Nothing commands temp) `catches`
```

as seen at https://hydra.nixos.org/build/135361157/nixlog/2

**Comment by jneira** [comment]
thanks for noting it, will add the upper bound in a hackage revision

**Comment by jneira** [comment]
@maralorn I've published the hackage revision with the upper bound: https://hackage.haskell.org/package/hls-hlint-plugin-0.1.0.0/revisions/

**Comment by jneira** [comment]
it should be buildable now, @maralorn feel free to reopen in other case
