### ISSUE TITLE
Build with GHC 8.10

### ISSUE THREAD

**Issue by chshersh** [haskell/haskell-language-server#937]
I'm trying to build `ghcide` using recently released GHC 8.10. After updating dependencies correspondingly, I see the following error message:

```
src/Development/IDE/GHC/HieAst.hs:30:1: error:
    Could not find module ‘HsSyn’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
30 | import HsSyn
   | ^^^^^^^^^^^^

src/Development/IDE/GHC/HieAst.hs:37:37: error:
    Module ‘Type’ does not export ‘mkFunTys’
   |
37 | import Type                       ( mkFunTys, Type )
   |                                     ^^^^^^^^
```

I can see that at least the `HsSyn` module is not present in `ghc-lib-parser-8.10.1.20200324`.

cc @pepeiborra
