### PR TITLE
Prepare 0.7.0 release (includes bump ghcide to 0.6.0.1)

### PR DESCRIPTION
**Pull request by jneira**
* This will not be the final commit ([ghcide has to be released yet](https://github.com/haskell/ghcide/pull/940)) but let's see what has to say ci.

### CODE REVIEW

**Review by alanz — APPROVED** [review]
Happy with this, once CI passes

**Comment by Ailrun** [comment]
Awesome! CI says there is an ambiguity for `findCradle`, but that's a minor problem.

**Comment by jneira** [comment]
stack build in circleci using stack-8.8.3.yaml and stack-8.8.2.yaml (and likely with stack-8.8.4.yaml) is failing with

```
Progress 166/173: ghcide ghcide > /root/build/ghcide/src/Development/IDE/Plugin/Completions/Logic.hs:267:5: error:
Progress 166/173: ghcide ghcide >     • Illegal equational constraint NoGhcTcPass pass
Progress 166/173: ghcide ghcide >                                     ~ NoGhcTcPass (NoGhcTcPass pass)
Progress 166/173: ghcide ghcide >       (Use GADTs or TypeFamilies to permit this)
Progress 166/173: ghcide ghcide >     • When checking the inferred type
Progress 166/173: ghcide ghcide >         f :: forall (pass :: Pass).
Progress 166/173: ghcide ghcide >              (Outputable.OutputableBndr
Progress 166/173: ghcide ghcide >                 (NameOrRdrName (IdP (GhcPass (NoGhcTcPass pass)))),
Progress 166/173: ghcide ghcide >               Outputable.OutputableBndr (IdP (GhcPass (NoGhcTcPass pass))),
Progress 166/173: ghcide ghcide >               Outputable.OutputableBndr (IdP (GhcPass pass)),
Progress 166/173: ghcide ghcide >               Outputable.OutputableBndr (NameOrRdrName (IdP (GhcPass pass))),
Progress 166/173: ghcide ghcide >               Outputable (XIPBinds (GhcPass pass)),
Progress 166/173: ghcide ghcide >               Outputable (XViaStrategy (GhcPass pass)),
Progress 166/173: ghcide ghcide >               Outputable (XIPBinds (GhcPass (NoGhcTcPass pass))),
Progress 166/173: ghcide ghcide >               Outputable (XViaStrategy (GhcPass (NoGhcTcPass pass))),
Progress 166/173: ghcide ghcide >               NoGhcTcPass pass ~ NoGhcTcPass (NoGhcTcPass pass)) =>
Progress 166/173: ghcide ghcide >              Maybe Range -> ImportDecl (GhcPass pass) -> Maybe [TextEdit]
Progress 166/173: ghcide ghcide >       In the expression:
Progress 166/173: ghcide ghcide >         let
Progress 166/173: ghcide ghcide >           f (Just range) ImportDecl {ideclHiding}
Progress 166/173: ghcide ghcide >             = case ideclHiding of
Progress 166/173: ghcide ghcide >                 Just (False, x)
Progress 166/173: ghcide ghcide >                   | Set.notMember name (Set.fromList ...) -> ...
Progress 166/173: ghcide ghcide >                   | otherwise -> ...
Progress 166/173: ghcide ghcide >                 _ -> ...
Progress 166/173: ghcide ghcide >           f _ _ = Nothing
Progress 166/173: ghcide ghcide >           src_span = srcSpanToRange . getLoc $ lDecl
Progress 166/173: ghcide ghcide >         in f src_span . unLoc $ lDecl
Progress 166/173: ghcide ghcide >       In an equation for ‘extendImportList’:
Progress 166/173: ghcide ghcide >           extendImportList name lDecl
Progress 166/173: ghcide ghcide >             = let
Progress 166/173: ghcide ghcide >                 f (Just range) ImportDecl {ideclHiding} = ...
Progress 166/173: ghcide ghcide >                 f _ _ = Nothing
Progress 166/173: ghcide ghcide >                 src_span = srcSpanToRange . getLoc $ lDecl
Progress 166/173: ghcide ghcide >               in f src_span . unLoc $ lDecl
Progress 166/173: ghcide ghcide >     |
Progress 166/173: ghcide ghcide > 267 |     f (Just range) ImportDecl {ideclHiding} = case ideclHiding of
Progress 166/173: ghcide ghcide >     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
Progress 166/173: ghcide ghcide > 
```
As ghcide is not being built with ghc-8.8 and stack anymore we dont get direct evidence if this error would be reproduced building ghcide standalone :thinking:

**Comment by jneira** [comment]
I've leveraged the new `findCradle` from the new ghcide session options and replacing hie-bios one with 03bd6d8

**Comment by jneira** [comment]
Nix builds in github are failing with
```
 building '/nix/store/5iw4gkavrvbyk9kqmfzbrr0mslyd39xa-cabal2nix-haskell-language-server.drv'...
installing
building '/nix/store/z6136irqnsp2qjwdics1aix0y0l0hmc2-cabal2nix-ghcide.drv'...
installing
error: anonymous function at /nix/store/fysbydywdhlim0yl5djdk4nm07402v96-cabal2nix-ghcide/default.nix:1:1 called without required argument 'shake-bench', at /nix/store/51gm3gjl7i2n3f7pamrbsckm4h0fmhy2-nixpkgs-src/pkgs/development/haskell-modules/make-package-set.nix:87:27
(use '--show-trace' to show detailed location information)
Error: Process completed with exit code 1.
```
I guess we have to change nix config files but i dont know how

**Comment by pepeiborra** [comment]
Does the comment at the top of `shell.nix` help?

https://github.com/haskell/haskell-language-server/blob/9120f4bea5225eba7927f35cb0d0b494c0fc35ac/shell.nix#L4

**Comment by jneira** [comment]
@pepeiborra yeah, I missed that config file, only took a quick look inside the nix dir

**Comment by jneira** [comment]
Ok, two issues blocks the pr now:
* builds for ghc-8.8.2 and 8.8.3 don't compile due to https://github.com/haskell/haskell-language-server/pull/658#issuecomment-741765495
* the recently enabled completion tests thanks to @peterwicksstringfield are failing with [timeouts](https://github.com/haskell/haskell-language-server/pull/658/checks?check_run_id=1527030715)
  * But they are succesful with actual version of ghcide, so 

@pepeiborra what do you think about add GADT's to the ghcide module to check if it fixes the issue and use that commit in hls? Ideally that version should be the last released one in hackage

@peterwicksstringfield could you take a quick look to completion tetsts to see if they can be fixed without too much effort? 
I am afraid that maybe we will need to mark them as broken again temporary to unblock the release.

**Comment by alanz** [comment]
I am wondering if the corners being cut in ghcide CI are worth it.

**Comment by pepeiborra** [comment]
> I am wondering if the corners being cut in ghcide CI are worth it.

Not related. We have cut `stack`, but we never had builds for 8.8.2 and 8.8.3. And yes, they are worth it.

**Comment by pepeiborra** [comment]
> * builds for ghc-8.8.2 and 8.8.3 don't compile due to [#658 (comment)](https://github.com/haskell/haskell-language-server/pull/658#issuecomment-741765495)
> @pepeiborra what do you think about add GADT's to the ghcide module to check if it fixes the issue and use that commit in hls? Ideally that version should be the last released one in hackage
> 
> @peterwicksstringfield could you take a quick look to completion tetsts to see if they can be fixed without too much effort?
> I am afraid that maybe we will need to mark them as broken again temporary to unblock the release. Assuming that features continue working.

We will have to add 8.8.2 and 8.8.3 to the test matrix in ghcide CI. I'll see to that.

**Comment by jneira** [comment]
> We will have to add 8.8.2 and 8.8.3 to the test matrix in ghcide CI. I'll see to that.

Many thanks, ideally ghcide should have the same matrix than hls, at least with cabal. So maybe we should add ghc-8.6.4 and ghc-8.10.1 too as they are missing in ghcide afair.

**Comment by jneira** [comment]
* fix building with ghc-8.8.3 and ghc-8.8.2 in https://github.com/haskell/ghcide/pull/947
* @pepeiborra ci pr adding missing ghc versions with https://github.com/haskell/ghcide/pull/946

**Comment by peterwicksstringfield** [comment]
I have no objections to re-disabling these tests for now.

In #668 I am attempting to fix the tests.

**Review by pepeiborra — APPROVED** [review]

**Comment by peterwicksstringfield** [comment]
You might have already seen it, but the failure on (ci/circleci: ghc-8.8.2) is something about a dependency on apply-refact.

**Comment by jneira** [comment]
Not sure why `brittany` and `floskell` have changed at once the order of imports from

```
import           Data.List
import           Prelude
import           Data.Int
```

to

```
import           Data.List
import           Data.Int
import           Prelude
```

but it seems the actual behaviour is right iirc so i've updated the golden files.

**Comment by jneira** [comment]
Nix is failing now with
```
Error: Action failed with error: Error: The process '/nix/var/nix/profiles/per-user/runner/profile/bin/cachix' failed with exit code 1
  (node:3080) UnhandledPromiseRejectionWarning: Error: The process '/nix/var/nix/profiles/per-user/runner/profile/bin/cachix' failed with exit code 1
      at ExecState._setResult (/home/runner/work/_actions/cachix/cachix-action/v8/dist/main/index.js:907:25)
      at ExecState.CheckComplete (/home/runner/work/_actions/cachix/cachix-action/v8/dist/main/index.js:890:18)
      at ChildProcess.<anonymous> (/home/runner/work/_actions/cachix/cachix-action/v8/dist/main/index.js:790:27)
      at ChildProcess.emit (events.js:210:5)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  (node:3080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:3080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I hope it is a transient one

**Comment by jneira** [comment]
I think #672 should be the last pr to be merged before cut the release version so please, dont merge additional pr's to master until the tag is created (if you think someone else should be included comment it out here or in the pr itself)

**Comment by jneira** [comment]
Waiting for ci... :roll_eyes:

**Comment by jneira** [comment]
> Hosted macOS workflows will experience longer wait times the week of December 14th. 

https://github.com/actions/virtual-environments/issues/2247

**Review by Ailrun — APPROVED** [review]
