### ISSUE TITLE
hls doesn't install on ghc 9.6.2

### ISSUE THREAD

**Issue by GeorgeCo** [haskell/haskell-language-server#3675]
### Your environment

GHC 9.6.2 installed via sudo make install
MacOS 13.4.1

### Steps to reproduce

cabal install hls

### Expected behaviour

Success

### Actual behaviour

...
[12 of 13] Compiling Graphics.PS.PS   ( Graphics/PS/PS.hs, dist/build/Graphics/PS/PS.o, dist/build/Graphics/PS/PS.dyn_o )

Graphics/PS/PS.hs:249:10: error: [GHC-39999]
    • Could not deduce ‘Semigroup (MonadMonoid m)’
        arising from the superclasses of an instance declaration
      from the context: Monad m
        bound by the instance declaration at Graphics/PS/PS.hs:249:10-42
    • In the instance declaration for ‘Monoid (MonadMonoid m)’
    |
249 | instance Monad m => Monoid (MonadMonoid m) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build hps-0.15 (which is required by hls-0.15).

**Comment by joyfulmantis** [comment]
HLS 0.15, is quite old and does nott support the latest version of GHC. The latest version is 2.0.0.0 and that builds with GHC 9.6.2. Consider using ghcup which [supports compiling HLS from source](https://www.haskell.org/ghcup/guide/#hls).

**Comment by michaelpj** [comment]
I'm going to close as this is for a very old version.
