### ISSUE TITLE
HLS ignores GHC plugins

### ISSUE THREAD

**Issue by JakobBruenker** [haskell/haskell-language-server#3299]
### Your environment

Ubuntu (under Windows 11 WSL)
ghc 9.4.2 via ghcup

Reproduction repo with minimal example:
https://github.com/JakobBruenker/plugin-test

Which LSP client (editor/plugin) do you use?
VS Code, but running haskell-language-server outside of it produces the same error

Which version of HLS do you use and how did you install it?
1.8.0.0 via ghcup

Have you configured HLS in any way (especially: a hie.yaml file)?
No (though an hie.yaml file generated via implicit-hie seemed to make no difference)

### Steps to reproduce

Clone the reproduction repo linked above and run `haskell-language-server` inside `just-some-project`.

NB: Because of #3297, this does not work if you run HLS in the top-level directory `plugin-test`.

### Expected behaviour

There should be no errors, since the plugin replaces `puStrLn` with `putStrLn`.

### Actual behaviour

HSL shows the error
```
  Variable not in scope: puStrLn :: String -> IO ()
  Suggested fix: Perhaps use ‘putStrLn’ (imported from Prelude)
```
Even though the plugin changes the name to `putStrLn`, which means `cabal run` works just fine.

Strangely, I seem to remember doing something similar 6 months ago and it worked, but now I can't get it to work with 9.2 either, but it may have been a different kind of plugin.

**Comment by michaelpj** [comment]
I think source plugins don't work, see e.g. https://github.com/haskell/haskell-language-server/issues/2779

I don't think anyone particularly knows why though. It probably needs a plugin champion!

**Comment by JakobBruenker** [comment]
Ah, I suppose this is a duplicate ticket then and can be closed?

I'm writing a plugin at the moment and am definitely considering fixing this after I'm done, so the plugin will actually be useful. Not sure yet if I'll be able to figure how out, though.

**Comment by fendor** [comment]
Issue is likely caused by us invoking the GHC API incorrectly :upside_down_face:

Since GHC 9.0, Plugins have moved to HscEnv from DynFlags, but we don't modify the HscEnv correctly, it seems to be a mistake from https://github.com/haskell/haskell-language-server/pull/2128
