### ISSUE TITLE
hls-test-utils-1.0.0.0 doesn't build with hspec-core 2.8

### ISSUE THREAD

**Issue by felixonmars** [haskell/haskell-language-server#1835]
### Your environment
Which OS do you use:
Arch Linux x86_64

### Steps to reproduce
Build hls-test-utils 1.0.0.0 with hspec-core 2.8

### Actual behaviour
```
Configuring hls-test-utils-1.0.0.0...
Preprocessing library for hls-test-utils-1.0.0.0..
Building library for hls-test-utils-1.0.0.0..
[1 of 2] Compiling Test.Hls.Util    ( src/Test/Hls/Util.hs, dist/build/Test/Hls/Util.dyn_o )

src/Test/Hls/Util.hs:188:32: error:
    ‘configOutputFile’ is not a (visible) constructor field name
    |
188 |                              , configOutputFile = Right $ subdir </> "results.xml"
    |                                ^^^^^^^^^^^^^^^^
```

It was removed in https://github.com/hspec/hspec/commit/86ad5be451d849e7711c342374798bfdfcbd4d33#diff-f0f01b0b2162c19117bc77a50a8986ec24c6553b1e09c83213cac5c6760b270f

**Comment by jneira** [comment]
Thanks for point it out. So as first action we have to add an upper bound and make a hackage revision to make it buildable

**Comment by berberman** [comment]
Afaik `getHspecFormattedConfig` is no longer used, and only tactics plugin is using `hspec` in test suite. We should clear out `hspec` related things from `hls-test-utils`.

**Comment by jneira** [comment]
Agree, but the upper bound an hackage revision will be needed.

**Comment by jneira** [comment]
Revision done: https://hackage.haskell.org/package/hls-test-utils-1.0.0.0/revision/1.cabal
